# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TZBasePro_OC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
#pod 'JLRoutes'
  # Pods for TZBasePro_OC

  target 'TZBasePro_OCTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Masonry'
  end

  target 'TZBasePro_OCUITests' do
    # Pods for testing
  end

end
